library(shiny)
library(lubridate)
library(ggplot2)
library(dplyr)

#Data set generated by "data_processing.R"
pricesqft <- readRDS("pricesqft.RDS")


shinyServer(function(input, output) {
    
    #Metro area selection - reactive checkboxes
    metro_area <- as.character(sort(unique(pricesqft$Metro)))
    values <- reactiveValues()
    
    #Default selected
    defaultMetro <- c("New York, NY", "San Francisco, CA", "Chicago, IL", "Dallas, TX", "Las Vegas, NV")
    values$metro_area <- defaultMetro
    
    # Zip Code selection checkboxes
    output$metro_select <- renderUI({
        checkboxGroupInput('metro_area', 'Select metro Area:', 
                           metro_area, selected = values$metro_area)
    })
    
    # Control for Select Default button
    observe({
        if(input$selectDefault == 0) return()
        values$metro_area <- defaultMetro
    })
    
    # Control for Clear All button
    observe({
        if(input$clearAll == 0) return()
        values$metro_area <- ""
    })
    
    # Control for reactive data set selection
    dataInput <- reactive({
        pricesqft %>% filter(Date >= ymd(paste(input$date_range[1], "01", "01")) & Date <= ymd(paste(input$date_range[2], "01", "01")) & Metro %in% input$metro_area)
    })
    
    
    
    # Control for plot rendering
    output$distPlot <- renderPlot({
    
        ggplot(dataInput(), aes(Date, Median, color = Metro)) +
            geom_line(size = 2) +
            xlab("Date") +
            ylab("Median Price Per Sq Ft")
    })
    
})
